### ISSUE TITLE
Question: new icons - how exactly?

### ISSUE THREAD

**Issue by pongraczi** [laravel-enso/MenuManager#10]
Hi,
I try to follow the doc and include some new icons in new menu items, but unfortunately my tries are failed.

So, steps:
- I added new menu items
- I added icon name for the menu item, called boxes  (variants I tried: boxes, Boxes, faBoxes, coffee, Coffee, faCoffee)
- I also added the icon name into the resources/assets/js/pages/layout/sidebar/icons/app.js (some variants, too):
```
import fontawesome from '@fortawesome/fontawesome';
import {
    coffee,
} from '@fortawesome/fontawesome-free-solid/shakable.es';
fontawesome.library.add([
    coffee,
]);
```
- as I can see, Enso uses fontawesome 4.7, right? (in this case, boxes will be missing as not part of 4.7)
- I try to find the icon name in the sourcecode, but I did not really figured out, how to add new icons (I guess, the name I try to use is not suitable somehow)

My question, where can I find a straightforward description, how to add new icons, what names I should use? Thanks!

**Comment by aocneanu** [comment]
Enso uses fa@5.0 since.. read the changelog.

faBoxes / faCoffee in the import will do, in the menus table use boxes / coffe.

**Comment by pongraczi** [comment]
Thank you!

I did the following:
- set boxes for one menu item and coffee for an other menu item
- I added to the import and fontawesome.library.add the faCoffe, faBoxes
- deleted browser cache
- php artisan serve restarted
- icons still empty
- console error log: 
![kijeloles_674](https://user-images.githubusercontent.com/5891983/37898487-38fb2e6c-30e9-11e8-9c8c-e60077ce35ac.png)


Do I need something else to get it work?

**Comment by aocneanu** [comment]
did you compile?

**Comment by pongraczi** [comment]
sh*t

**Comment by aocneanu** [comment]
Please always close tickets if they are resolved, or here it's not the case?

**Comment by pongraczi** [comment]
I will, but still compiling.

**Comment by pongraczi** [comment]
Seems I have to upgrade npm to 4.7.x from 3.5.2 (on my local dev machine).

**Comment by pongraczi** [comment]
Ok, switched to ppa, now npm run dev is running, but must rerun from npm install.....

**Comment by pongraczi** [comment]
Seems I messed up everything with old npm/upgrade npm...  
So, I am working on eliminate all compiling problems I run into...

**Comment by pongraczi** [comment]
Thank you, after compiling (npm run dev) I got it working as expected.  
Is there any rule, how to use the name of the icon?  
I mean, using `faIconname` in import and the simple `iconname` in the menu entry should work? (using fa as prefix and upper case letter as first character)  
(after your answer, the ticket should be closed, thanks)

**Comment by aocneanu** [comment]
There is more to consider. Please start from here:

https://fontawesome.com/get-started

**Comment by pongraczi** [comment]
Thanks!
