### ISSUE TITLE
Setup an url as route in the menu

### ISSUE THREAD

**Issue by albertosgz** [laravel-enso/MenuManager#15]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
How to setup a link in the menu.

### Steps to Reproduce
I tried to add a new menu, and only allow me setup internal and predefined routes. I can't see any place to setup an URL.

### Expected behavior
Setup a link, relative to same domain or external site.

### Actual behavior
I can't do it.

Thanks!

**Comment by aocneanu** [comment]
We rely solely on named routes. We have a global front-end `route` helper that will translate any named route to an url. It works exactly like Laravel's `route` function.

**Comment by albertosgz** [comment]
I will find find out the global route later and let you know if it works out.

**Comment by albertosgz** [comment]
Sure. Thanks!
