### ISSUE TITLE
Menu icon missing

### ISSUE THREAD

**Issue by cosimolemma** [laravel-enso/MenuManager#9]
Hi,
when I try to insert a new menu voice, icon is missing in datatable and sidebar menu. I tried lots of fontawesome icons such as cloud, facebook, etc but only already known icons (such as cloud-upload-alt) are rendered in the Menu table and sidebar. What could I do to solve this? Thanks!

**Comment by aocneanu** [comment]
Hi,

Please take a look at laravel-enso/Core#37. You will see the steps to add custom icons.

Will add soon the the main doc / menu manger doc this info.

**Comment by cosimolemma** [comment]
It works like a charm. Thanks a lot!

**Comment by aocneanu** [comment]
We'll leave this open until we update the docs. It might help somebody else.
